### PR TITLE
TODO: accept input as apk

### PR DESCRIPTION
**Pull request by AbhiTheModder**

### CODE REVIEW

**Comment by worawit** [comment]
IMHO, temporary directory for extracting apk should be deleted after finishing a program. This can be done with `tempfile.TemporaryDirectory` by using a context manager `with tempfile.TemporaryDirectory() as tmpdirname:`.

Currently, blutter supports only arm64-v8a architecture, the extraction should check for `arm64-v8a` only. Also extracting only `libapp.so` and `libflutter.so` should be enough.

**Comment by AbhiTheModder** [comment]
> IMHO, temporary directory for extracting apk should be deleted after finishing a program. This can be done with `tempfile.TemporaryDirectory` by using a context manager `with tempfile.TemporaryDirectory() as tmpdirname:`.

If we use this and delete the temperory directory then program will have no path to `libapp.so` and `libflutter.so` to work further as needed by `extract_dart_info` and `libapp_file` for the subprocess of blutter to run.

However we can consider clearing the temp directory after subprocess completion that can be good idea.

> Currently, blutter supports only arm64-v8a architecture, the extraction should check for `arm64-v8a` only. Also extracting only `libapp.so` and `libflutter.so` should be enough.

Indeed, thanks for this suggestion.

**Comment by worawit** [comment]
Could you allow me editing your pull request?

The instruction for setting is at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by AbhiTheModder** [comment]
> Could you allow me editing your pull request?
> 
> The instruction for setting is at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Please feel free to do so... it's already enabled:
image

**Comment by worawit** [comment]
don't know why I still cannot push a commit.

just merge and edit it.

**Pull request merged**
